### ISSUE TITLE
Unloading 3 folders causes unloading of other plugins

### ISSUE THREAD

**Issue by higps** [nosoop/SM-PluginMangler#2]
I have 3 folders with additional plugins for a gamemode, that is to be disabled.

On the server.cfg of the folder it does the following commands

sm_plugins unload /mm/
sm_plugins unload /mmattributes/
sm_plugins unload /mmrobots/

On the server that doesn't unload, all other plugins work fine.

However on all the servers that unloaded these 3 folders, only a fraction of the other plugins were loaded. Functions such as sm_map or sm_rcon was not loaded.

Removing the sm_mangler plugin fixed the issue, so there's something wrong when it unloads certain plugins that it stops the loading of others.

I have 150 plugins total with these 3 folders

Is there any specific data I need to provide in this instance?

**Comment by higps** [comment]
I've done some more testing, every time I unload plugins in the server.cfg it stops loading other plugins. When I remove this plugin all plugins load normally

**Comment by nosoop** [comment]
Parameters wrapped in forward slashes indicates that the parameter is a regular expression &mdash; `/mm/` is matching the "mm" in `basecommands.smx` and unloading it.  This is intended behavior.

If you want to unload the contents of the `mm/` subdirectory you'll want something like `/mm\/.*$/` (the paths currently aren't normalized; you may want to capture both slash forms if you're working with Windows paths).
